# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'BookSeeker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookSeeker
  pod 'Cartography', '4.0'
  pod 'SwiftGen', '6.1'
  pod 'SwiftLint'
  pod 'Kingfisher', '5.11.0'
  pod 'Alamofire', '4.9.1'
end
